name: LFPAnalysis
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py310h5764c6d_1005
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2024.7.4=hbcca054_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - cryptography=39.0.0=py310h34c0648_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.6=py310heca2aa9_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.0.1=py_1001
  - executing=1.2.0=pyhd8ed1ab_0
  - fooof=1.0.0=pyh5ca1d4c_0
  - freetype=2.12.1=hca18f0e_1
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - ipyevents=2.0.1=pyhd8ed1ab_0
  - ipykernel=6.19.4=pyh210e3f2_0
  - ipython=8.8.0=pyh41d4057_0
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_2
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py310hff52083_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py310hbf28c38_1
  - lcms2=2.14=hfd0df8a_1
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=16_linux64_openblas
  - libdeflate=1.17=h0b41bf4_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - libjpeg-turbo=2.1.4=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.39=h753d276_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.13=h166bdaf_4
  - markupsafe=2.1.2=py310h1fa729e_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - nbstripout=0.7.1=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - neurodsp=2.2.0=pyhd8ed1ab_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openpyxl=3.0.10=py310h5764c6d_2
  - openssl=3.3.1=h4bc722e_2
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py310h9b08913_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310h4927cde_0
  - pip=22.3.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - psutil=5.9.4=py310h5764c6d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py310h1fa729e_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.8=h4a9ceb5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyzmq=25.0.0=py310h059b190_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.2=pyhd8ed1ab_0
  - scipy=1.10.0=py310h8deb116_0
  - seaborn=0.12.1=hd8ed1ab_0
  - seaborn-base=0.12.1=pyhd8ed1ab_0
  - setuptools=66.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py310hde88566_2
  - tk=8.6.12=h27826a3_0
  - tornado=6.2=py310h5764c6d_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.8.1=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - widgetsnbextension=4.0.5=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.11.0=pyhd8ed1ab_0
  - zstd=1.5.2=h6239696_4
  - pip:
      - babel==2.16.0
      - cftime==1.6.3
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.2.0
      - dcor==0.6
      - distributed==2023.11.0
      - emd==0.5.5
      - fcwt==0.1.18
      - fonttools==4.47.2
      - fsspec==2023.10.0
      - ghp-import==2.1.0
      - h5io==0.1.9
      - h5py==3.9.0
      - joblib==1.2.0
      - lazy-loader==0.3
      - levenshtein==0.20.9
      - llvmlite==0.39.1
      - locket==1.0.0
      - markdown==3.7
      - matplotlib==3.8.2
      - mergedeep==1.3.4
      - mkdocs==1.6.1
      - mkdocs-get-deps==0.2.0
      - mkdocs-material==9.5.42
      - mkdocs-material-extensions==1.3.1
      - mne==1.6.1
      - mne-connectivity==0.7.0.dev0
      - msgpack==1.0.7
      - netcdf4==1.6.5
      - numba==0.56.4
      - numpy==1.23.5
      - paginate==0.5.7
      - partd==1.4.1
      - pathspec==0.12.1
      - pycatch22==0.4.2
      - pygments==2.18.0
      - pymdown-extensions==10.11.2
      - pyyaml==6.0
      - pyyaml-env-tag==0.1
      - rapidfuzz==2.13.7
      - regex==2024.9.11
      - scikit-base==0.5.1
      - scikit-learn==1.3.0
      - sktime==0.22.0
      - sortedcontainers==2.4.0
      - sparse==0.13.0
      - tabulate==0.9.0
      - tblib==3.0.0
      - tensorpac==0.6.5
      - threadpoolctl==3.2.0
      - toolz==0.12.0
      - watchdog==5.0.3
      - xarray==2024.1.1
      - zict==3.0.0
prefix: /sc/arion/work/qasims01/test-env/envs/LFPAnalysis
